## Biblioteca Numpy



Numpy é tão importante pelo fato dela ser projetada para ser muito eficaz com array de dados muito grandes.

Todos os elemtenso em um ndarray sao do mesmo tipo



In [1]:
import numpy as np

In [3]:
# Gerar um NDArray 2x3 (duas listas com 3 elementos)
dados = np.random.rand(2,3)
dados

array([[0.60416626, 0.38194166, 0.74357656],
       [0.69232663, 0.97419179, 0.4573681 ]])

In [4]:
# Tipo de array
dados.dtype

dtype('float64')

In [5]:
# Tamanho e quantidade de dimensoes
dados.shape

(2, 3)

In [8]:
dados.ndim

2

Criar ndarray usando a finçao array

In [9]:
lista = [1,2,5,7,8,1.25]

In [11]:
dados2 = np.array(lista)
dados2

array([1.  , 2.  , 5.  , 7.  , 8.  , 1.25])

como contem um array na lista, todos os numeros quando passados para um ndarray seram floats, pois todos os elementos sao iguais num ndarray.

In [12]:
lista2 = [[1,2,3,4],[4,3,2,1]]

In [13]:
dados3 = np.array(lista2)
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

já aqui todos os numero sao inteiros(int)

Outras maneiras de criar arrays

In [ ]:
# funçao de array todos zeros
dadoszero= np.zeros(10)
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
dadoszero2 = np.zeros((2,3))
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
dadosum = np.ones(5)
dadosum

array([1., 1., 1., 1., 1.])

criaçao de array com numeros 1


In [18]:
dadosseq = np.arange(10)
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Criando array com dados sequencias

In [20]:
# criando array com dados sequencias do 0 ao 20 com passo 2
dadosseq2 = np.arange(0,20,2)
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
dadosseq.dtype

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [ ]:
# Alterando o tipo de dados do array
dadosseqf = dadosseq.astype(np.float64)
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Aritimetica com arrays


In [26]:
dados4 = np.array([[1,2,3],[4,5,6]])
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
dados4 * dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [28]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
dados5 = dados4+dados4
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

Indexação


In [34]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
dadosseq[5]

np.int64(5)

---------

In [36]:
dadosseq[3:6]

array([3, 4, 5])

In [37]:
dadosseq[3:6]=20

In [38]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [40]:
fatiadados = dadosseq[2:4]
fatiadados  

array([ 2, 20])

In [42]:
fatiadados[1]=2000
fatiadados

array([   2, 2000])

In [43]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [44]:
fatiadados[:]=333
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Copiar dados


In [45]:
fatia2 =dadosseq[2:4].copy()
fatia2

array([333, 333])

In [46]:
fatia2[:]=111
fatia2

array([111, 111])

In [47]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Array com mais de uam dimensão

In [49]:
dados6 = np.array([[1,2,3],[4,5,6],[7,8,9]])
dados6


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
dados6[1,2]

np.int64(6)

nota-se que o numero que aparece nessa busca é o 6, pos esta na linha 1 e na coluna 2

Mascaras

In [52]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [54]:
mascara = (dadosseq<100)
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

gerar uma comparação(resposta em booleano, TRUE ou FAlSE)

In [55]:
dadosseq[dadosseq<20]=888
dadosseq

array([888, 888, 333, 333,  20,  20, 888, 888, 888, 888])

atribuindo o valor 888 aos valores que são menores que 20

Transposição

In [ ]:
dados7 = np.arange(15).reshape((3,5))

# O reshepe reorganiza o array, nesse exempplo para 3 listas com 5 intens em cada

In [62]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [58]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Tranposição dos numeros dentro do array

Multiplicação de Matrizes com Dots

In [63]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])